baseURL: https://kaihg.github.io

languageCode: en-us
title: "KK(Kaihg) CV"
theme: "toha"

# Manage languages
# # For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1


# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # background: "images/kk-logo.png"

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/kaihg/kaihg.github.io
  gitBranch: master
  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  newsletter:
    enable: false

